server:
  port: 7002
  error:
    include-message: always

spring.application.name: recommendation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  cloud:
    function:
      definition: process
    stream:
      function:
        bindings:
          process-in-0: input
      bindings:
        input:
          consumer:
            paratitoned: true
            instanceCount: 1
            instanceIndex: 0
          group: recommendations
          destination: recommendations
      default-binder: kafka
      kafka:
        bindings.input.consumer:
          enableDlq: true
        binder:
          configuration:
            auto.offset.reset: earliest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
  mongodb:
    embedded:
      version: 3.4.5

logging:
  level:
    root: INFO
    dev.minz: DEBUG

---
spring:
  profiles: docker

server.port: 8080

spring.cloud.stream.kafka.binder.brokers: kafka

eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka"

spring.data.mongodb.host: mongodb
