server:
  port: 7002
  error:
    include-message: always

spring:
  cloud:
    function:
      definition: process
    stream:
      function:
        bindings:
          process-in-0: input
      bindings:
        input:
          group: recommendation
          destination: recommendation
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
  mongodb:
    embedded:
      version: 3.4.5

logging:
  level:
    root: INFO
    dev.minz: DEBUG

---
spring:
  profiles: docker

  data:
    mongodb:
      host: mongodb

server:
  port: 8080
