server:
  port: 7001

spring:
  cloud:
    function:
      definition: process
    stream:
      function:
        bindings:
          process-in-0: input
      bindings:
        input:
          consumer:
            paratitoned: true
            instanceCount: 1
            instanceIndex: 0
          group: products
          destination: products
      default-binder: kafka
      kafka:
        bindings.input.consumer:
          enableDlq: true
        binder:
          configuration:
            auto.offset.reset: earliest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
  mongodb:
    embedded:
      version: 3.4.5

logging:
  level:
    root: INFO
    dev.minz.microservices: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  profiles: docker

  data:
    mongodb:
      host: mongodb

server:
  port: 8080

spring.cloud.stream.kafka.binder.brokers: kafka
