server:
  port: 7003
  error:
    include-message: always

spring:
  cloud:
    function:
      definition: process
    stream:
      function:
        bindings:
          process-in-0: input
      bindings:
        input:
          consumer:
            paratitoned: true
            instanceCount: 1
            instanceIndex: 0
          group: reviews
          destination: reviews
      default-binder: kafka
      kafka:
        bindings.input.consumer:
          enableDlq: true
        binder:
          configuration:
            auto.offset.reset: earliest
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000

logging:
  level:
    root: INFO
    dev.minz: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql/review-db

server:
  port: 8080

spring.cloud.stream.kafka.binder.brokers: kafka
